# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
np.empty((3,3,3))

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
        [1.95820216e-306, 4.45055939e-308, 1.20161594e-306],
        [1.89146896e-307, 7.56571288e-307, 4.00544531e-307]],

       [[1.11261095e-306, 1.15710088e-306, 1.78022342e-306],
        [1.60217812e-306, 1.11261570e-306, 1.20160236e-306],
        [9.34605716e-307, 8.45562698e-307, 7.56591658e-307]],

       [[1.27945567e-307, 8.06631290e-308, 9.79067808e-307],
        [1.22383391e-307, 9.34568368e-307, 8.01061221e-307],
        [9.79065771e-307, 1.15706964e-306, 2.33423131e-312]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [4]:
np.diag(1+np.arange(4), k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [65]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [27]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.12649703 0.25283212 0.10556308 0.58523415 0.24158034]
 [0.54739341 0.86916224 0.08915871 0.32068203 0.27248199]
 [0.44861409 0.03275358 0.33774104 0.86278744 0.46066311]
 [0.36989864 0.39924466 0.63754603 0.7834293  0.91753133]
 [0.78887659 0.50978678 0.19563951 0.96326347 0.77097206]]
After normalization:
[[0.10074417 0.23651392 0.07824689 0.59373961 0.22442187]
 [0.55307293 0.89887133 0.06061745 0.30943084 0.25763124]
 [0.44691681 0.         0.3277638  0.89202046 0.45986565]
 [0.36232292 0.39386049 0.64995811 0.80673589 0.9508526 ]
 [0.81258997 0.51265785 0.1750502  1.         0.79334834]]


# 5.  How to find common values between two arrays?

In [66]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)

np.intersect1d(a, b)

array([1, 4, 7])

# 6.How to get the dates of yesterday, today and tomorrow?

In [67]:
yest = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tom  = np.datetime64('today') + np.timedelta64(1)
print(yest, today, tom)

2020-07-27 2020-07-28 2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [30]:
a=np.random.random((3,3))
b=np.random.random((3,3))
if a.all()==b.all():
    print('They are equal')
else:
    print('They are not equal')

They are equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [68]:
a = np.random.rand(10)
a[a.argmax()] = 0
a

array([0.71925862, 0.73385418, 0.43373272, 0.72983878, 0.70080681,
       0.        , 0.42024475, 0.51518361, 0.32000529, 0.51541847])

# 9. How to print all the values of an array?

In [52]:
a=np.random.random((2,2))
print(a)

[[0.57677937 0.24611699]
 [0.84601864 0.0974901 ]]


# 10.Subtract the mean of each row of a matrix

In [54]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
m1=a[0].mean()
m2=a[1].mean()
m3=a[2].mean()
print(m1-m2-m3)

-11.0


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [70]:
a = np.ones(5)
b = np.random.randint(0, len(a), 10)
a += np.bincount(b, minlength = len(a))
a

array([3., 6., 1., 1., 4.])

# 12.How to get the diagonal of a dot product?

In [71]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", a, b)

array([75, 24, 42])

# 13.How to find the most frequent value in an array?

In [73]:
a = np.random.randint(0,10,20)
print(a)
max(set(a), key = list(a).count)

[0 0 2 1 3 7 7 5 3 0 9 4 1 6 4 7 6 5 5 7]


7

# 14.How to get the n largest values of an array

In [55]:
a=np.random.random((3,3))
print(a.max())

0.843499125745257


# 15.How to create a record array from a regular array?

In [74]:
arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])